try fixing now error with function name change (is there a conflict?)
The error is:

Error: from SVG Render: Evaluation failed: ReferenceError: getSvg is not
defined
    at __puppeteer_evaluation_script__:1:17